# Site settings
title: regine erika
email: kikay.vo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl:  # the subpath of your site, e.g. /blog/
url: https://regineerika.github.io # the base hostname & protocol for your site
github_username:  regineerika
instagram_username: regine_erika

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-email-protect
  
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  chocoMilk:
    output: true
    permalink: /chocoMilk/:path/
    
mini_magick:
  photoFolders:
      source: img/photoportfolio
      destination: thumbnails/img/photoportfolio
      resize: "320x240^"
      gravity: "center"
      extent: "320x240"

exiftag:
 sources:
   - photos
   - photos/other_source
